# Integrantes



*   Luis Alejandro Montoya
*   Juan Sebastian Villada
*   Christian Daniel España

In [2]:
import pandas as pd
import numpy as np

#**Ejercicio 1**

Construya un DataFrame a partir del siguiente diccionario

`exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, 10, 9, 20, 14.5, 12, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}`

con las siguientes etiquetas para los índices

`labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']`

* Seleccione solo las columnas *name* y *score*.
  
* Filtre las filas donde el número de intentos (attemps) sea mayor que 2.

* Filtre las filas donde el *score* se encuentre entre 15 y 20 (incluidos)

* Cambie el *score* en la fila 'd' a 11.5

* Agregue una nueva fila con etiqueta 'k' al dataframe con un valor que usted desee para cada columna

* Borre la fila 'k' y entregue nuevamente el DataFrame original.

* Ordene el DataFrame por nombre en orden ascendente.

* Reemplace los valores de la columna *qualify* que contiene los valores *yes* y *no* por los valores booleanos True y False respectivamente.

In [ ]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, 10, 9, 20, 14.5, 12, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
df = pd.DataFrame(data = exam_data, index = labels)
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   10.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura   12.0         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes



1.   Seleccione solo las columnas name y score.

In [ ]:
df.loc[:,['name', 'score']]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James   10.0
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura   12.0
i      Kevin    8.0
j      Jonas   19.0



2.   Filtre las filas donde el número de intentos (attemps) sea mayor que 2.

In [ ]:
df[df['attempts'] > 2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James   10.0         3      no
f  Michael   20.0         3     yes



3.   Filtre las filas donde el score se encuentre entre 15 y 20 (incluidos)

In [ ]:
df[(df['score'] >= 15) & (df['score'] <= 20)]

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes



4.   Cambie el score en la fila 'd' a 11.5

In [ ]:
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   10.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura   12.0         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [ ]:
df.loc["d", 'score'] = 11.5

In [ ]:
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura   12.0         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes



5.   Agregue una nueva fila con etiqueta 'k' al dataframe con un valor que usted desee para cada columna

In [ ]:
dic = {'name':'Carlos',
       'score': 7.0,
       'attempts': 10,
       'qualify':'yes'}

In [ ]:
df.loc['k', :] = dic

In [ ]:
df

        name  score  attempts qualify
a  Anastasia   12.5       1.0     yes
b       Dima    9.0       3.0      no
c  Katherine   16.5       2.0     yes
d      James   10.0       3.0      no
e      Emily    9.0       2.0      no
f    Michael   20.0       3.0     yes
g    Matthew   14.5       1.0     yes
h      Laura   12.0       1.0      no
i      Kevin    8.0       2.0      no
j      Jonas   19.0       1.0     yes
k     Carlos    7.0      10.0     yes



6.   Borre la fila 'k' y entregue nuevamente el DataFrame original.

In [ ]:
df.drop(index = 'k', inplace = True, axis = 1)

In [ ]:
df

        name  score  attempts qualify
a  Anastasia   12.5       1.0     yes
b       Dima    9.0       3.0      no
c  Katherine   16.5       2.0     yes
d      James   10.0       3.0      no
e      Emily    9.0       2.0      no
f    Michael   20.0       3.0     yes
g    Matthew   14.5       1.0     yes
h      Laura   12.0       1.0      no
i      Kevin    8.0       2.0      no
j      Jonas   19.0       1.0     yes



7.   Ordene el DataFrame por nombre en orden ascendente.

In [ ]:
df.sort_values(by = ['name'], inplace = True)
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
e      Emily    9.0         2      no
d      James   10.0         3      no
j      Jonas   19.0         1     yes
c  Katherine   16.5         2     yes
i      Kevin    8.0         2      no
h      Laura   12.0         1      no
g    Matthew   14.5         1     yes
f    Michael   20.0         3     yes



8.       Reemplace los valores de la columna qualify que contiene los valores yes y no por los valores booleanos True y False respectivamente.

In [ ]:
df['qualify']= df['qualify'].map({'yes':True,
                   'no': False})

In [ ]:
df

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
e      Emily    9.0         2    False
d      James   10.0         3    False
j      Jonas   19.0         1     True
c  Katherine   16.5         2     True
i      Kevin    8.0         2    False
h      Laura   12.0         1    False
g    Matthew   14.5         1     True
f    Michael   20.0         3     True

# Ejercicio 2



1.   Importarlo como nombre athletes

In [3]:
athletes = pd.read_csv('https://raw.githubusercontent.com/tomasate/Datos_Clases/main/Datos_1/athletes.csv')

In [ ]:
athletes.head(12)

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze
0,736041664,A Jesus Garcia,ESP,male,10/17/69,1.72,64.0,athletics,0,0,0
1,532037425,A Lam Shin,KOR,female,9/23/86,1.68,56.0,fencing,0,0,0
2,435962603,Aaron Brown,CAN,male,5/27/92,1.98,79.0,athletics,0,0,1
3,521041435,Aaron Cook,MDA,male,1/2/91,1.83,80.0,taekwondo,0,0,0
4,33922579,Aaron Gate,NZL,male,11/26/90,1.81,71.0,cycling,0,0,0
5,173071782,Aaron Royle,AUS,male,1/26/90,1.80,67.0,triathlon,0,0,0
6,266237702,Aaron Russell,USA,male,6/4/93,2.05,98.0,volleyball,0,0,1
7,382571888,Aaron Younger,AUS,male,9/25/91,1.93,100.0,aquatics,0,0,0
8,87689776,Aauri Lorena Bokesa,ESP,female,12/14/88,1.80,62.0,athletics,0,0,0
9,997877719,Ababel Yeshaneh,ETH,female,7/22/91,1.65,54.0,athletics,0,0,0
10,343694681,Abadi Hadis,ETH,male,11/6/97,1.70,63.0,athletics,0,0,0
11,591319906,Abbas Abubakar Abbas,BRN,male,5/17/96,1.75,66.0,athletics,0,0,0


2.   Filtre el dataframe tal que solo se quede con los atletas que hayan ganado al menos una medalla.

In [ ]:
%%time
athletes[(athletes["gold"]>0 ) | (athletes["silver"]>0 ) | ((athletes["bronze"]>0 ) ) ]

CPU times: user 4.23 ms, sys: 0 ns, total: 4.23 ms
Wall time: 3.93 ms

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze,num_medallas
2,435962603,Aaron Brown,CAN,male,5/27/92,1.98,79.0,athletics,0,0,1,1
6,266237702,Aaron Russell,USA,male,6/4/93,2.05,98.0,volleyball,0,0,1,1
14,162792594,Abbey Weitzeil,USA,female,12/3/96,1.78,68.0,aquatics,1,1,0,2
48,962468808,Abdoulrazak Issoufou Alfaga,NIG,male,12/26/94,2.07,98.0,taekwondo,0,1,0,1
55,969824503,Abdullah Alrashidi,IOA,male,8/21/63,1.83,84.0,shooting,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
11487,334126873,Zhiyong Shi,CHN,male,10/10/93,1.68,69.0,weightlifting,1,0,0,1
11491,105609876,Zi He,CHN,female,12/10/90,1.60,52.0,aquatics,0,1,0,1
11503,593183472,Zivko Gocic,SRB,male,8/22/82,1.93,93.0,aquatics,1,0,0,1
11509,836633838,Zoe Lee,GBR,female,12/15/85,1.76,70.0,rowing,0,1,0,1
11511,343671816,Zoe de Toledo,GBR,female,7/17/87,1.72,58.0,rowing,0,1,0,1



3.   Calcule la masa muscular por fila con una función como

In [ ]:
def masa_muscular(row):
  """
  Esta función realiza el calculo de la masa muscular como funcion del peso y la estatura de los atletas



  Parametros Entrada

  row: fila del dataframe


  Retorna

  el calculo de la masa corporal

  """
  return round(((row["weight"])/(row["height"]**2)), 2)

In [ ]:
athletes['Masa_Muscular'] = athletes.apply(masa_muscular, axis = 1)

In [ ]:
athletes

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze,num_medallas,Masa_Muscular
0,736041664,A Jesus Garcia,ESP,male,10/17/69,1.72,64.0,athletics,0,0,0,0,21.63
1,532037425,A Lam Shin,KOR,female,9/23/86,1.68,56.0,fencing,0,0,0,0,19.84
2,435962603,Aaron Brown,CAN,male,5/27/92,1.98,79.0,athletics,0,0,1,1,20.15
3,521041435,Aaron Cook,MDA,male,1/2/91,1.83,80.0,taekwondo,0,0,0,0,23.89
4,33922579,Aaron Gate,NZL,male,11/26/90,1.81,71.0,cycling,0,0,0,0,21.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11533,265605954,Zurian Hechavarria,CUB,female,8/10/95,1.64,58.0,athletics,0,0,0,0,21.56
11534,214461847,Zuzana Hejnova,CZE,female,12/19/86,1.73,63.0,athletics,0,0,0,0,21.05
11535,88361042,di Xiao,CHN,male,5/14/91,1.85,100.0,wrestling,0,0,0,0,29.22
11536,900065925,le Quoc Toan Tran,VIE,male,4/5/89,1.60,56.0,weightlifting,0,0,0,0,21.87
11537,711404576,le Roux Hamman,RSA,male,1/6/92,1.85,70.0,athletics,0,0,0,0,20.45



4.   Agrupe los datos  calculando la media por deporte para cada una del resto de características. ¿Cuál es el deporte en el que los jugadores tienen mayor peso promedio?

In [5]:
weight_mean_men = athletes.groupby(by = ['sport'])[['weight']].mean()
weight_mean_men.sort_values(by = 'weight', ascending=False)

                      weight
sport
basketball         87.750000
handball           83.710602
volleyball         80.102094
weightlifting      79.980620
rowing             79.938318
rugby sevens       78.723906
wrestling          77.742120
canoe              77.015291
judo               76.876316
shooting           73.905263
tennis             73.162304
aquatics           72.301644
archery            72.190476
golf               71.443478
sailing            71.169355
fencing            70.661224
hockey             68.900463
badminton          68.774390
football           68.433962
taekwondo          68.088000
cycling            67.820717
athletics          67.717727
equestrian         67.493023
modern pentathlon  65.958333
table tennis       65.177515
triathlon          60.633028
gymnastics         54.278997
boxing                   NaN

In [6]:
print(f"El deporte que tiene los jugadores con mayor peso promedio es: {weight_mean_men.idxmax(axis = 0)[0]}")

El deporte que tiene los jugadores con mayor peso promedio es: basketball



5.   ¿Cuál es el pais con más participación femenina?

In [7]:
women_plays = athletes[athletes["sex"]=="female"].groupby(by = ['nationality'])[["sex"]].count()
women_plays.sort_values(by = 'sex', ascending=False)

             sex
nationality
USA          303
CHN          251
AUS          220
BRA          216
GER          204
...          ...
SOM            1
SSD            1
STP            1
ASA            1
AFG            1

[202 rows x 1 columns]

In [8]:
print(f"El pais que contiene mayor mujeres participantes es: {women_plays.idxmax(axis = 0)[0]}")

El pais que contiene mayor mujeres participantes es: USA

# **Ejercicio 3**

Importe el dataset de nba del repositorio de clase y responda (hint: Elimine las instancias con registros faltantes)

In [10]:
nba = pd.read_csv('https://raw.githubusercontent.com/tomasate/Datos_Clases/main/Datos_1/nba.csv')
nba

,Unnamed: 0,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...,...
453,453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
nba.isnull().sum()

Unnamed: 0     0
Name           1
Team           1
Number         1
Position       1
Age            1
Height         1
Weight         1
College       85
Salary        12
dtype: int64

In [12]:
nba.dropna(inplace = True)

In [13]:
nba.isnull().sum()

Unnamed: 0    0
Name          0
Team          0
Number        0
Position      0
Age           0
Height        0
Weight        0
College       0
Salary        0
dtype: int64



1.   Cuáles son los equipos que pagan los salarios más altos (presente el resultado como un dataFrame con el nombre del equipo y la cantidad de dinero de la nómina)

In [14]:
table = pd.pivot_table(nba, values=['Salary'], index=["Team"], aggfunc={'Salary': np.sum})

In [16]:
table =table.sort_values(by = ['Salary'], ascending=False).head()
table

                           Salary
Team
Los Angeles Clippers   93906914.0
Oklahoma City Thunder  81515298.0
Golden State Warriors  80535517.0
Cleveland Cavaliers    74068189.0
Chicago Bulls          73265800.0



2.   Separe la variable Age en tres grupos y cree una nueva columna llamada Age-Group con esta información.

In [17]:
nba.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,364.0,2.245989e+02,1.314983e+02,0.0,112.5,220.5,336.25,456.0
Number,364.0,1.682967e+01,1.499416e+01,0.0,5.0,12.0,25.00,99.0
Age,364.0,2.661538e+01,4.233591e+00,19.0,24.0,26.0,29.00,40.0
Weight,364.0,2.197857e+02,2.479310e+01,161.0,200.0,220.0,240.00,279.0
Salary,364.0,4.620311e+06,5.119716e+06,55722.0,1000000.0,2515440.0,6149694.25,22875000.0

In [18]:
nba['Age-Group'] = pd.cut(x=nba['Age'], bins=[19, 25, 35, 40])

In [19]:
nba

,Unnamed: 0,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Age-Group
0,0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,"(19, 25]"
1,1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,"(19, 25]"
3,3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,"(19, 25]"
6,6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0,"(19, 25]"
7,7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0,"(19, 25]"
...,...,...,...,...,...,...,...,...,...,...,...
449,449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0,"(19, 25]"
451,451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0,"(25, 35]"
452,452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0,"(19, 25]"
453,453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,"(25, 35]"
456,456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,"(25, 35]"



3.   Construya una tabla dinámica que muestre el salario promedio de los jugadores por equipo y posición para para los cinco equipos que pagan mejores salarios.

Nota: En la lista top_5 se almacenan los nombres de los 5 equipos con los salarios promedio mas altos hallados en el primer punto y se usa esta lista para filtrar el dataframe y se muestra la informacion solicitada solo para dichos equipos

In [20]:
table.head(5).index

Index(['Los Angeles Clippers', 'Oklahoma City Thunder',
       'Golden State Warriors', 'Cleveland Cavaliers', 'Chicago Bulls'],
      dtype='object', name='Team')

In [21]:
top_5 = table.head(5).index
table0 = pd.pivot_table(nba[nba.Team.isin(top_5)], index = ["Team", "Position"], values = ["Salary"], aggfunc={'Salary': np.mean})

In [22]:
table0

                                      Salary
Team                  Position
Chicago Bulls         C         1.340000e+07
                      PF        3.578740e+06
                      PG        1.117153e+07
                      SF        1.958160e+06
                      SG        5.717549e+06
Cleveland Cavaliers   C         7.768435e+06
                      PF        1.394101e+07
                      PG        6.551592e+06
                      SF        9.472760e+05
                      SG        3.349079e+06
Golden State Warriors C         6.541249e+06
                      PF        1.426087e+07
                      PG        1.137079e+07
                      SF        3.766367e+06
                      SG        8.224138e+06
Los Angeles Clippers  C         1.039480e+07
                      PF        6.655482e+06
                      PG        1.228975e+07
                      SF        3.662924e+06
                      SG        4.639893e+06
Oklahoma City Thunder C         6.303143e+06
                      PF        2.606520e+06
                      PG        9.382869e+06
                      SF        8.599621e+06
                      SG        3.207058e+06

In [1]:
pwd

'/content'

In [1]:
cd /content/drive/MyDrive/Especializacion

/content/drive/MyDrive/Especializacion

In [2]:
cd Fundamentos_Clases

/content/drive/MyDrive/Especializacion/Fundamentos_Clases

In [4]:
pwd

'/content/drive/MyDrive/Especializacion/Fundamentos_Clases'

In [5]:
!git --version

git version 2.34.1

In [6]:
!git init

Reinitialized existing Git repository in /content/drive/MyDrive/Especializacion/Fundamentos_Clases/.git/

In [31]:
!git config --global user.name "Christian España"

In [32]:
!git config --global user.email christian.espana1@gmail.com

In [34]:
!git checkout -b mi_branch_new_2

Switched to a new branch 'mi_branch_new_2'

In [35]:
!git status

On branch mi_branch_new_2
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Pandas1.ipynb
	modified:   Pandas2.ipynb
	modified:   Pandas3.ipynb
	modified:   Tarea_2_Especializacion.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	"Copia de Contenido Fundamentos en Programacio\314\201n - Contenidos.pdf"
	"Estadi\314\201stica_y_MC.ipynb"
	Tarea 1 Especializacion.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [3]:
!git add Tarea_2_Especializacion.ipynb

In [42]:
!ls

'Copia de Contenido Fundamentos en Programación - Contenidos.pdf'
 Estadística_y_MC.ipynb
 Funciones_Clases.ipynb
 Linux_Ubuntu_Python.ipynb
 Miscelanius.ipynb
 Numpy_II.ipynb
 Numpy_I.ipynb
 Pandas1.ipynb
 Pandas2.ipynb
 Pandas3.ipynb
 Plotting.ipynb
 Prueba_1.ipynb
'Tarea 1 Especializacion.ipynb'
 Tarea_2_Especializacion.ipynb

In [4]:
!git commit -m "Se envia la solucion del la tarea 2"

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@69478cbfed58.(none)')

In [5]:
!git config --global user.email "christian.espana1@gmail.com"

In [28]:
!git config --global user.name cdspana

In [29]:
!git add Tarea_2_Especializacion.ipynb

In [30]:
!git commit -m "Se envia la solucion del la tarea 2"

[mi_branch_new_2 165c6d3] Se envia la solucion del la tarea 2
 1 file changed, 1 insertion(+), 1 deletion(-)

In [31]:
!git push origin main

fatal: could not read Username for 'https://github.com': No such device or address

In [24]:
!git status

On branch mi_branch_new_2
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Pandas1.ipynb
	modified:   Pandas2.ipynb
	modified:   Pandas3.ipynb
	modified:   Tarea_2_Especializacion.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	"Copia de Contenido Fundamentos en Programacio\314\201n - Contenidos.pdf"
	"Estadi\314\201stica_y_MC.ipynb"
	Tarea 1 Especializacion.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [18]:
!git commit -m "Se envia la solucion del la tarea 2"

[mi_branch_new 3d69dc9] Se envia la solucion del la tarea 2
 1 file changed, 1 insertion(+), 1 deletion(-)

In [19]:
!git status

On branch mi_branch_new
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Pandas1.ipynb
	modified:   Pandas2.ipynb
	modified:   Pandas3.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	"Copia de Contenido Fundamentos en Programacio\314\201n - Contenidos.pdf"
	"Estadi\314\201stica_y_MC.ipynb"
	Tarea 1 Especializacion.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [20]:
!git push origin mi_branch_new

fatal: could not read Username for 'https://github.com': No such device or address

In [21]:
!git status

On branch mi_branch_new
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Pandas1.ipynb
	modified:   Pandas2.ipynb
	modified:   Pandas3.ipynb
	modified:   Tarea_2_Especializacion.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	"Copia de Contenido Fundamentos en Programacio\314\201n - Contenidos.pdf"
	"Estadi\314\201stica_y_MC.ipynb"
	Tarea 1 Especializacion.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [23]:
!git checkout main

error: Your local changes to the following files would be overwritten by checkout:
	Tarea_2_Especializacion.ipynb
Please commit your changes or stash them before you switch branches.
Aborting

In [24]:
!git add Tarea_2_Especializacion.ipynb

In [25]:
!git commit -m "Se envia la solucion del la tarea 2"

[mi_branch_new 5361e9e] Se envia la solucion del la tarea 2
 1 file changed, 1 insertion(+), 1 deletion(-)

In [28]:
!git push origin main

fatal: could not read Username for 'https://github.com': No such device or address

In [29]:
!git merge origin/master

merge: origin/master - not something we can merge

In [30]:
!git status

On branch mi_branch_new
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Pandas1.ipynb
	modified:   Pandas2.ipynb
	modified:   Pandas3.ipynb
	modified:   Tarea_2_Especializacion.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	"Copia de Contenido Fundamentos en Programacio\314\201n - Contenidos.pdf"
	"Estadi\314\201stica_y_MC.ipynb"
	Tarea 1 Especializacion.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [ ]:
!git config --global user.name "TuNombreDeUsuario"

In [35]:
!git config --global user.name
!git config --global user.email

cdspana
christian.espana1@gmail.com

In [34]:
!git remote -v

origin	https://github.com/tomasate/Fundamentos_Clases (fetch)
origin	https://github.com/tomasate/Fundamentos_Clases (push)